#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /tmp
#  file: /tmp/log/tomcat/sell.log
#  level: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.136/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
